version: '3.8'

services:
  jenkins-server:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network

  jenkins-agent:
    image: ctg135/jenkins-python:latest
    container_name: jenkins-agent
    restart: unless-stopped
    environment:
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_AGENT_NAME=agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=a939b0cf188d2ef03551090145fbd4974e67dc3725d8475e0bdeb5677f053663
    volumes:
      - agent_workdir:/home/jenkins/agent
    depends_on:
      - jenkins-server
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  agent_workdir:

networks:
  jenkins-network: